grafana:
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false
      editable: false
alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: "null"
      group_by:
        - alertname
        - service
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 5m
      routes:
        - receiver: api-webhook
          matchers:
            - 'severity = "critical"'
            - 'service = "api"'

    receivers:
      - name: "null"

      - name: api-webhook
        webhook_configs:
          - url: http://alert-receiver.monitoring.svc.cluster.local/alerts
            send_resolved: true
