spring.application.name=api
server.port=8080

management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=prometheus
management.endpoints.web.path-mapping.prometheus=metrics
management.metrics.tags.service=${spring.application.name}

server.error.include-message=always
