apiVersion: v1
kind: Pod
metadata:
  name: bad-labels
  namespace: shop
spec:
  containers:
    - name: app
      image: nginx
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"