apiVersion: v1
kind: Pod
metadata:
  name: missing-probes

spec:
  containers:
    - name: api
      image: registry.local/shop/api:1.0.0
      imagePullPolicy: IfNotPresent

      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 256Mi