apiVersion: v1
kind: Pod
metadata:
  name: privileged

spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.10

      securityContext:
        privileged: true

      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi

      readinessProbe:
        exec:
          command: ["true"]
      livenessProbe:
        exec:
          command: ["true"]
    