replicaCount: 1

image:
  repository: ghcr.io/prymitive/karma
  pullPolicy: IfNotPresent
  tag: v0.133

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

env:
  - name: ALERTMANAGER_URI
    value: http://monitoring-kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  - name: ALERTMANAGER_NAME
    value: lab2
  - name: ALERTMANAGER_READONLY
    value: "true"

ingress:
  enabled: false

httpRoute:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

autoscaling:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}