apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-image-tag
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: [shop]
      validate:
        message: "Запрещён тег :latest и отсутствие тега — указывайте конкретную версию"
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ images.containers.{{ element.name }}.tag }}"
                    operator: AnyIn
                    value: ["", "latest"]