provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

storage:
  type: memory

allInOne:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

agent:
  enabled: false

collector:
  enabled: false

query:
  enabled: false