spring.application.name=shop-api
server.port=8080

health.fail=${HEALTH_FAIL:false}

spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:shop}
spring.datasource.username=${DB_USER:shop}
spring.datasource.password=${DB_PASSWORD:shop}
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:10}
spring.sql.init.mode=always

management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=prometheus
management.endpoints.web.path-mapping.prometheus=metrics
management.metrics.tags.service=${spring.application.name}

server.error.include-message=always
