replicaCount: 1

image:
  repository: api
  tag: "0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

env:
  PORT: "5000"
  SELF_URL: "http://localhost:5000"
  OTEL_SERVICE_NAME: "api"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"

serviceMonitor:
  enabled: true