apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    owner: shop
spec:
  selector:
    app: api
  ports:
    - port: 80
      name: http
      targetPort: 8000
  type: ClusterIP