apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    owner: shop
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: shop
      owner: shop
      secret:
        name: postgres-app-secret
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: shop
  password: shop